import { test, expect } from '@playwright/test';

test('subsession has a bounded transcript, visible composer, and explicit identity-bound mentions', async ({ page }, testInfo) => {
  await page.goto('/tests/visual/subsessionConversation.html');
  await page.getByRole('button', { name: 'Open background agent session: Planet research' }).click();
  const panel = page.locator('[data-chat-side-agent-panel="true"]');
  await expect(panel).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByText('Parent conversation remains here.', { exact: true })).toBeVisible();
  const panelBounds = await panel.boundingBox();
  expect(panelBounds!.x).toBeGreaterThan(0);
  expect(panelBounds!.width).toBeLessThan(page.viewportSize()!.width);
  const field = panel.getByRole('textbox');
  await expect(panel.getByText('Ask Agent · Planet research', { exact: true })).toBeVisible();
  await expect(panel.getByText('Queued next', { exact: true })).toHaveCount(2);
  await expect(panel.locator('.app-queued-message').filter({ hasText: 'Owner queued follow' })).toContainText('Alex');
  await expect(field).toBeVisible();
  const bounds = await field.boundingBox();
  expect(bounds!.y + bounds!.height).toBeLessThan(page.viewportSize()!.height);
  await field.fill('Hello everyone');
  await panel.getByRole('button', { name: 'Send to Planet research', exact: true }).click();
  await expect.poll(() => page.evaluate(() => (window as unknown as {sentSubsessionRequests: {mentions: unknown[]}[]}).sentSubsessionRequests[0]?.mentions.length)).toBe(0);
  await expect(field).toBeEditable();
  await expect(field).toHaveText('');
  await field.pressSequentially('@Kordi');
  await page.getByRole('option').filter({ hasText: "Alex's Kordi" }).click();
  await expect(field).toContainText('@KordiAlex');
  await page.evaluate(() => {
    const snapshot = (window as unknown as {fixtureSubsession: {agentDisplayName: string; version: number}}).fixtureSubsession;
    snapshot.agentDisplayName = 'Research Agent'; snapshot.version += 1;
  });
  await expect(page.getByText('Research Agent · Owner · Alex', { exact: true })).toBeVisible();
  await field.pressSequentially(' continue');
  await panel.getByRole('button', { name: 'Send to Planet research', exact: true }).click();
  await expect.poll(() => page.evaluate(() => (window as unknown as {sentSubsessionRequests: unknown[]}).sentSubsessionRequests[1])).toEqual({ clientMessageId: expect.any(String), text: expect.stringMatching(/^@KordiAlex\s+continue$/), mentions: [expect.objectContaining({ agentId: 'fixture-agent' })] });
  await expect(page.getByText('processing...', { exact: true })).toHaveCount(0);
  expect(await page.evaluate(() => (window as unknown as {unexpectedParentSends:number}).unexpectedParentSends)).toBe(0);
  expect(await page.evaluate(() => (window as unknown as {unexpectedNativePrefetches:number}).unexpectedNativePrefetches)).toBe(0);
  await page.screenshot({ path: testInfo.outputPath('conversation.png') });
  await page.evaluate(() => {
    const snapshot = (window as unknown as {fixtureSubsession: {status: string; version: number; messages: {requestState?: string}[]}}).fixtureSubsession;
    snapshot.status = 'done'; snapshot.version += 1;
    for (const message of snapshot.messages) if (message.requestState) message.requestState = 'completed';
  });
  await expect(page.locator('[data-related-agent-session-status="done"]')).toBeVisible();
  await panel.getByRole('button', { name: 'Close side chat', exact: true }).click();
  await expect(panel).toHaveCount(0);
  await page.getByRole('button', { name: 'Open background agent session: Planet research' }).click();
  await expect(panel.getByText('Hello everyone', { exact: true })).toBeVisible();
  await expect(panel).toHaveAttribute('data-companion-session-id', 'fixture-child');
  await expect(page.getByRole('dialog')).toHaveCount(0);
});

test('side-panel follow-up failures retain the draft and retry the same request identity', async ({ page }) => {
  await page.goto('/tests/visual/subsessionConversation.html');
  await page.getByRole('button', { name: 'Open background agent session: Planet research' }).click();
  const panel = page.locator('[data-chat-side-agent-panel="true"]');
  const field = panel.getByRole('textbox');
  await field.fill('Retry this member message');
  await page.evaluate(() => { (window as unknown as {failNextSubsessionSend:boolean}).failNextSubsessionSend = true; });
  await panel.getByRole('button', { name: 'Send to Planet research' }).click();
  await expect(panel.getByRole('alert')).toContainText('Could not send');
  await expect(field).toHaveText('Retry this member message');
  await panel.getByRole('button', { name: 'Send to Planet research' }).click();
  await expect(field).toHaveText('');
  const requests = await page.evaluate(() => (window as unknown as {sentSubsessionRequests: {clientMessageId:string}[]}).sentSubsessionRequests);
  expect(requests).toHaveLength(2);
  expect(requests[0].clientMessageId).toBe(requests[1].clientMessageId);
  expect(await page.evaluate(() => (window as unknown as {unexpectedParentSends:number}).unexpectedParentSends)).toBe(0);
});
