import { createContext, useContext, useEffect, useLayoutEffect, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { Bell, RefreshCw } from 'lucide-react';
import { digestClient } from './client';
import { useDigest } from './useDigest';
import { connectedCalendars, fetchCalendarLink, dateKey, importCalendar, readDeviceEvents, syncReminders, type CalendarImport } from './calendar';
import type { CalendarConnection, CalendarEvent, DigestItem, DigestSource } from './types';
import { DigestCalendar, DigestAgenda } from './DigestCalendar';
import { calendarErrorMessage, importCalendarEvents, type CalendarImportReport } from './calendarImport';
import './digest.css';

const timeLabel=(value:string)=>new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const localInput=(value?:string|null)=>{if(!value)return '';const d=new Date(value);return `${dateKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
const ActionErrorContext = createContext<{error:string|null;setError:(error:string|null)=>void}>({error:null,setError:()=>{}});
function Sheet({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
  const ref=useRef<HTMLDialogElement>(null);
  const {error,setError}=useContext(ActionErrorContext);
  useEffect(()=>{setError(null);ref.current?.showModal();return()=>setError(null);},[setError]);
  return <dialog className="digest-sheet" ref={ref} onCancel={onClose}><header><h2>{title}</h2><button onClick={onClose}>Close</button></header>{error&&<p role="alert" className="digest-warning">{error}</p>}{children}</dialog>;
}
export default function DigestPage({accountId}:{accountId:string}){
  const {digest,events,error,reload,calendarLoaded}=useDigest(accountId);
  const [view,setView]=useState<'brief'|'tasks'|'calendar'>('brief');
  const mainRef=useRef<HTMLDivElement>(null);
  const scrollPositions=useRef({brief:0,tasks:0,calendar:0});
  useLayoutEffect(()=>{if(mainRef.current)mainRef.current.scrollTop=scrollPositions.current[view];},[view]);
  const [month,setMonth]=useState(()=>dateKey(new Date()).slice(0,7));
  const [selectedDay,setSelectedDay]=useState(()=>dateKey(new Date()));
  const [sourceId,setSourceId]=useState<string|string[]|null>(null);
  const [editItem,setEditItem]=useState<DigestItem|null>(null);
  const [editEvent,setEditEvent]=useState<CalendarEvent|null>(null);
  const [importOpen,setImportOpen]=useState(false);
  const [connections,setConnections]=useState<CalendarConnection[]|null>(null);
  const [busy,setBusy]=useState(false);const [actionError,setActionError]=useState<string|null>(null);
  const [reminderState,setReminderState]=useState('unknown');
  const sources=digest?.sources??[];const output=digest?.snapshot;
  const selectedSources=sources.filter(s=>(Array.isArray(sourceId)?sourceId:[sourceId]).includes(s.id)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
  const source=selectedSources[0];
  const feedback=digest?.feedback??[];
  const openTasks=(output?.commitments??[]).filter(i=>i.kind!=='done');
  const eventSignature=JSON.stringify(events.map(e=>({id:e.id,title:e.title,startAt:e.startAt,reminderAt:e.reminderAt,revision:e.revision})));
  useEffect(()=>{if(!calendarLoaded)return;let cancelled=false;void syncReminders(accountId,JSON.parse(eventSignature) as CalendarEvent[]).then(value=>{if(!cancelled)setReminderState(value);}).catch(()=>{if(!cancelled)setReminderState('error');});return()=>{cancelled=true;};},[accountId,eventSignature,calendarLoaded]);
  async function act(operation:()=>Promise<unknown>){setBusy(true);setActionError(null);try{await operation();await reload();}catch(e){setActionError(calendarErrorMessage(e,'Could not complete this action.'));try{await reload();}catch{/* Retain the visible action error. */}}finally{setBusy(false);}}
  async function saveImported(incoming:CalendarEvent[]){
    const current=await digestClient.calendar(accountId);
    const report=await importCalendarEvents(incoming,current.events,event=>digestClient.saveEvent(accountId,event));
    await reload();return report;
  }
  const visibleActionError=sourceId||editItem||editEvent||importOpen||connections?null:actionError;
  function people(item:DigestItem){
    const related=sources.filter(s=>item.sourceIds.includes(s.id));
    const unique=[...new Map(related.map(s=>[s.senderAccountId,s])).values()];
    return <div className="digest-people">{item.ownerAccountId&&<span>Owner @{item.ownerAccountId===accountId?'You':sources.find(s=>s.senderAccountId===item.ownerAccountId)?.senderName||'Contact'}</span>}{unique.filter(s=>s.senderAccountId!==item.ownerAccountId).map(s=><button key={s.senderAccountId} onClick={()=>void act(async()=>{await reload();setSourceId(s.id);})}>From @{s.isAgent?s.senderName:s.senderAccountId===accountId?'You':s.senderName}</button>)}</div>;
  }
  function evidence(item:DigestItem){
    const groups=new Map<string,DigestSource[]>();
    for(const id of item.sourceIds){const source=sources.find(s=>s.id===id);if(source)groups.set(source.sessionId,[...(groups.get(source.sessionId)??[]),source]);}
    return <div className="digest-evidence">{[...groups.entries()].map(([sessionId,group])=><button key={sessionId} onClick={()=>void act(async()=>{await reload();setSourceId(group.map(s=>s.id));})}>↗ {group[0].sessionTitle}{group.length>1?` · ${group.length} messages`:''}</button>)}</div>;
  }
  function calendarCandidate(item:DigestItem){const existing=events.find(e=>e.id===`digest-${item.id}`);setEditEvent(existing??{id:`digest-${item.id}`,title:item.title,startAt:item.startAt??'',endAt:item.endAt,reminderAt:null,allDay:false,description:item.text,sourceIds:item.sourceIds,revision:0});}
  function changeMonth(next:string){setMonth(next);if(!selectedDay.startsWith(next))setSelectedDay(`${next}-01`);}
  return <ActionErrorContext.Provider value={{error:actionError,setError:setActionError}}><section className="digest-page" aria-label="Digest"><header className="digest-header"><div><h1>Digest</h1><div className="digest-header-actions"><button aria-label="Enable calendar reminders" onClick={()=>void act(async()=>setReminderState(await syncReminders(accountId,events,true)))}><Bell size={18}/></button><button aria-label="Refresh digest" disabled={busy||digest?.status==='updating'} onClick={()=>void act(()=>digestClient.refresh(accountId))}><RefreshCw size={18}/></button></div></div><div className="digest-status"><span>{digest?.status==='updating'?'Updating · previous brief available':digest?.updatedAt?`Updated ${timeLabel(digest.updatedAt)}`:'Preparing your digest'}</span><span className="digest-live"><i aria-hidden="true"/> Updates with your conversations</span></div><nav aria-label="Digest views">{(['brief','tasks','calendar'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='brief'?'Brief':v==='tasks'?'Next steps':'Calendar'}</button>)}</nav></header>
    <div className="digest-notices" role="status">{(visibleActionError||error)&&<p className="digest-warning">{visibleActionError||error}</p>}{digest?.errorCode&&<p className="digest-warning">{digest.errorCode==='missing_provider_auth'?'Connect a model provider in account settings to generate your digest.':'The last update could not finish. Your previous brief remains available.'}</p>}{digest?.partial&&<p className="digest-warning">Partial coverage. This digest uses a bounded selection of accessible messages.</p>}{reminderState==='denied'&&<p className="digest-warning">Device notifications are off. Enable them in system settings to receive reminders.</p>}</div><div className="digest-body">
      <div className="digest-content-grid"><div className="digest-main" ref={mainRef} role="region" aria-label="Digest content" tabIndex={0} onScroll={event=>{scrollPositions.current[view]=event.currentTarget.scrollTop;}}>
      <section hidden={view!=='brief'} aria-label="Brief">{output?.claims.length?output.claims.map(item=><article className="digest-row" key={item.id}><h3>{item.title}</h3><p>{item.text}</p>{people(item)}{evidence(item)}</article>):<p className="digest-empty">{digest?.status==='ready'?'No conversations to summarize yet.':digest?.status==='error'?'Refresh after checking your provider connection.':'Your sourced brief will appear here after the first update.'}</p>}</section>
      <section hidden={view!=='tasks'} aria-label="Next steps"><h2>Commitments</h2>{openTasks.map(item=>{const linked=feedback.find(f=>f.id===item.id&&f.status==='task');return <article className="digest-row" key={item.id}><h3>{item.title}</h3>{people(item)}<p className="digest-meta">{item.kind==='possible'?'Possible follow-up · ':''}{item.dueAt?`Due ${timeLabel(item.dueAt)}`:'No due date'}{!item.ownerAccountId?' · Owner not specified':''}</p>{evidence(item)}{linked?<span className="digest-meta">Already a task</span>:<button disabled={busy} onClick={()=>setEditItem(item)}>Review task</button>}</article>;})}{openTasks.length===0&&<p className="digest-empty">No open commitments.</p>}<h2>Consider next <small>AI suggestions</small></h2>{output?.suggestions.filter(i=>!feedback.some(f=>f.id===i.id&&f.status==='dismissed')).map(item=><article className="digest-row" key={item.id}><h3>{item.title}</h3><p>{item.text}</p>{people(item)}{evidence(item)}<button onClick={()=>void act(()=>digestClient.feedback(accountId,item.id,true))}>Dismiss</button></article>)}{feedback.some(f=>f.status==='dismissed')&&<button onClick={()=>void act(async()=>{for(const f of feedback.filter(f=>f.status==='dismissed'))await digestClient.feedback(accountId,f.id,false);})}>Restore dismissed suggestions</button>}</section>
      <section hidden={view!=='calendar'} aria-label="Calendar"><DigestCalendar month={month} selectedDay={selectedDay} events={events} candidates={output?.calendarCandidates??[]} onMonth={changeMonth} onDay={setSelectedDay} onEvent={setEditEvent} onCandidate={calendarCandidate}/></section>
      </div><DigestAgenda day={selectedDay} events={events} candidates={output?.calendarCandidates??[]} people={people} evidence={evidence} onEvent={setEditEvent} onCandidate={calendarCandidate} onConnect={()=>void act(async()=>setConnections(await connectedCalendars()))} onImport={()=>setImportOpen(true)}/></div>
    </div>
    {sourceId&&<Sheet title={source?.sessionTitle||'Source unavailable'} onClose={()=>setSourceId(null)}>{source?<>{selectedSources.map(source=><article key={source.id}><p className="digest-meta">@{source.senderName} · {timeLabel(source.createdAt)}</p><blockquote>{source.text}</blockquote></article>)}</>:<p>This message is no longer included or accessible. Refresh the digest.</p>}</Sheet>}
    {editItem&&editItem.sourceIds.every(id=>sources.some(s=>s.id===id))&&<TaskEditor key={editItem.id} item={editItem} sources={sources} accountId={accountId} onClose={()=>setEditItem(null)} onSave={input=>act(async()=>{await digestClient.task(accountId,editItem.id,input);setEditItem(null);})}/>}
    {editEvent&&editEvent.sourceIds.every(id=>sources.some(s=>s.id===id))&&<EventEditor key={editEvent.id} event={editEvent} onClose={()=>setEditEvent(null)} onSave={event=>act(async()=>{await digestClient.saveEvent(accountId,event);setEditEvent(null);})} onRemove={editEvent.revision?()=>act(async()=>{await digestClient.removeEvent(accountId,editEvent);setEditEvent(null);}):undefined}/>}
    {importOpen&&<ImportSheet events={events} onClose={()=>setImportOpen(false)} onImport={saveImported}/>}
    {connections&&<ConnectSheet calendars={connections} onClose={()=>setConnections(null)} onImport={async ids=>{const from=new Date(),to=new Date();to.setFullYear(to.getFullYear()+1);return saveImported(await readDeviceEvents(ids,from.toISOString(),to.toISOString()));}}/>}
  </section></ActionErrorContext.Provider>;
}
function TaskEditor({item,sources,accountId,onClose,onSave}:{item:DigestItem;sources:DigestSource[];accountId:string;onClose:()=>void;onSave:(input:{title:string;ownerAccountId:string|null;dueAt:string|null})=>Promise<void>}){
  const [title,setTitle]=useState(item.title),[owner,setOwner]=useState(item.ownerAccountId??''),[due,setDue]=useState(localInput(item.dueAt));
  const owners=[...new Map(sources.filter(s=>item.sourceIds.includes(s.id)).map(s=>[s.senderAccountId,s.senderName])).entries()];
  return <Sheet title="Review task" onClose={onClose}><form onSubmit={e=>{e.preventDefault();void onSave({title,ownerAccountId:owner||null,dueAt:due?new Date(due).toISOString():null});}}><label>Title<input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Owner<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Unassigned</option><option value={accountId}>You</option>{owners.filter(([id])=>id!==accountId).map(([id,name])=><option key={id} value={id}>{id===accountId?'You':name}</option>)}</select></label><label>Due date<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><p className="digest-meta">A task is created only after you confirm.</p><footer><button type="button" onClick={onClose}>Cancel</button><button type="submit">Create task</button></footer></form></Sheet>;
}
function EventEditor({event,onClose,onSave,onRemove}:{event:CalendarEvent;onClose:()=>void;onSave:(event:CalendarEvent)=>Promise<void>;onRemove?:()=>Promise<void>}){
  const [title,setTitle]=useState(event.title),[start,setStart]=useState(event.allDay?event.startAt.slice(0,10):localInput(event.startAt)),[end,setEnd]=useState(event.allDay?event.endAt?.slice(0,10)||'':localInput(event.endAt)),[minutes,setMinutes]=useState(event.reminderAt?String(Math.round((new Date(event.startAt).getTime()-new Date(event.reminderAt).getTime())/60000)):'');
  const [error,setError]=useState<string|null>(null);
  function save(e:FormEvent){e.preventDefault();const startAt=new Date(event.allDay?`${start}T00:00:00Z`:start).toISOString();const endAt=end?new Date(event.allDay?`${end}T00:00:00Z`:end).toISOString():null;if(endAt&&endAt<startAt){setError('End cannot be before start.');return;}const reminderAt=minutes!==''?new Date(new Date(startAt).getTime()-Number(minutes)*60000).toISOString():null;if(reminderAt&&new Date(reminderAt)<new Date()){setError('That reminder time has passed. Choose No reminder or a later date.');return;}void onSave({...event,title,startAt,endAt,reminderAt});}
  return <Sheet title={event.revision?'Edit event':'Review calendar event'} onClose={onClose}><form onSubmit={save}><label>Title<input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{event.allDay?'Start date':'Start time'}<input required type={event.allDay?'date':'datetime-local'} value={start} onChange={e=>setStart(e.target.value)}/></label><label>{event.allDay?'End date (exclusive)':'End time (optional)'}<input type={event.allDay?'date':'datetime-local'} value={end} onChange={e=>setEnd(e.target.value)}/></label>{!event.allDay&&<label>Remind me<select value={minutes} onChange={e=>setMinutes(e.target.value)}><option value="">No reminder</option><option value="0">At start</option><option value="5">5 minutes before</option><option value="15">15 minutes before</option><option value="60">1 hour before</option></select></label>}<p className="digest-meta">{Intl.DateTimeFormat().resolvedOptions().timeZone} · Personal calendar. No invitations are sent.</p>{event.description&&<blockquote>{event.description}</blockquote>}{error&&<p role="alert">{error}</p>}<footer>{onRemove&&<button type="button" onClick={()=>void onRemove()}>Remove event</button>}<button type="button" onClick={onClose}>Cancel</button><button type="submit">{event.revision?'Save event':'Add to calendar'}</button></footer></form></Sheet>;
}
function ImportSheet({events,onClose,onImport}:{events:CalendarEvent[];onClose:()=>void;onImport:(events:CalendarEvent[])=>Promise<CalendarImportReport>}){
  const [report,setReport]=useState<CalendarImportReport|null>(null);
  const [link,setLink]=useState('');
  const [text,setText]=useState(''),[preview,setPreview]=useState<CalendarImport|null>(null),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false);
  const [from,setFrom]=useState(dateKey(new Date()));const [to,setTo]=useState(()=>{const date=new Date();date.setFullYear(date.getFullYear()+1);return dateKey(date);});
  async function parse(){setBusy(true);setError(null);try{const data=await importCalendar(text,from,to);setPreview(data);setSelected(new Set(data.events.filter(e=>!events.some(old=>old.id===e.id||old.externalUid===e.externalUid)).map(e=>e.id)));}catch(e){setError(e instanceof Error?e.message:'Could not import calendar.');}finally{setBusy(false);}}
  return <Sheet title={report?'Import complete':preview?'Review import':'Import ICS'} onClose={onClose}>{error&&<p role="alert">{error}</p>}{report?<ImportReport report={report} onClose={onClose}/>:preview?<><p>{selected.size} occurrences selected</p>{preview.warnings.map(w=><p className="digest-warning" key={w}>{w}</p>)}<div className="digest-import-list">{preview.events.map(e=><label key={e.id}><input type="checkbox" checked={selected.has(e.id)} disabled={events.some(old=>old.id===e.id||old.externalUid===e.externalUid)} onChange={v=>setSelected(old=>{const next=new Set(old);if(v.target.checked)next.add(e.id);else next.delete(e.id);return next;})}/><span>{e.title}<small>{e.allDay?e.startAt.slice(0,10):timeLabel(e.startAt)}</small></span></label>)}</div><p className="digest-meta">Alarms and invitations are not imported. You can set reminders after reviewing an event.</p><footer><button onClick={()=>setPreview(null)}>Back</button><button disabled={!selected.size||busy} onClick={()=>{setBusy(true);setError(null);void onImport(preview.events.filter(e=>selected.has(e.id))).then(setReport).catch(error=>setError(calendarErrorMessage(error,'Could not import events.'))).finally(()=>setBusy(false));}}>Import selected</button></footer></>:<><label>Paste calendar text<textarea rows={8} value={text} onChange={e=>setText(e.target.value)} placeholder="BEGIN:VCALENDAR…"/></label><label>Choose .ics file<input type="file" accept=".ics,text/calendar" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1_000_000){setError('Choose a file smaller than 1 MB.');return;}void file.text().then(setText);}}/></label><details><summary>Import from a calendar link</summary><label>HTTPS or webcal link<input type="url" value={link} onChange={e=>setLink(e.target.value)} autoComplete="off"/></label><button disabled={busy||!link.trim()} onClick={()=>{setBusy(true);void fetchCalendarLink(link).then(text=>{setText(text);setLink('');}).catch(e=>setError(e instanceof Error?e.message:'Could not fetch calendar.')).finally(()=>setBusy(false));}}>Load calendar text</button><p className="digest-meta">One-time import. The link is not stored.</p></details><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Before<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><p className="digest-meta">One-time import, up to one year. Floating times use this device’s timezone.</p><footer><button onClick={onClose}>Cancel</button><button disabled={!text.trim()||busy} onClick={()=>void parse()}>{busy?'Reading…':'Preview events'}</button></footer></>}</Sheet>;
}
function ImportReport({report,onClose}:{report:CalendarImportReport;onClose:()=>void}){
  return <><p>{report.imported} {report.imported===1?'event':'events'} imported.{report.duplicates>0?` ${report.duplicates} already in your calendar.`:''}</p>{report.skipped.length>0&&<><p>{report.skipped.length} {report.skipped.length===1?'event was':'events were'} skipped. Review their details in the source calendar.</p><ul className="digest-import-list">{report.skipped.map((event,index)=><li key={index}><strong>{event.title}</strong><p className="digest-meta">{event.reason}</p></li>)}</ul></>}<footer><button onClick={onClose}>Done</button></footer></>;
}
function ConnectSheet({calendars,onClose,onImport}:{calendars:CalendarConnection[];onClose:()=>void;onImport:(ids:string[])=>Promise<CalendarImportReport>}){
  const [selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[report,setReport]=useState<CalendarImportReport|null>(null);
  async function run(){setBusy(true);setError(null);try{setReport(await onImport(selected));}catch(error){setError(calendarErrorMessage(error,'Could not import calendars.'));}finally{setBusy(false);}}
  return <Sheet title={report?'Import complete':'Choose calendars'} onClose={onClose}>{report?<ImportReport report={report} onClose={onClose}/>:<><p>Choose calendars connected to this device. Their events will be copied into your private Kordi calendar.</p>{error&&<p role="alert">{error}</p>}{calendars.map(c=><label className="digest-choice" key={c.id}><input type="checkbox" disabled={busy} checked={selected.includes(c.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,c.id]:s.filter(id=>id!==c.id))}/>{c.title}</label>)}<p className="digest-meta">No invitations are sent. Source calendars stay unchanged.</p><footer><button disabled={busy} onClick={onClose}>Cancel</button><button disabled={!selected.length||busy} onClick={()=>void run()}>{busy?'Importing…':'Import selected calendars'}</button></footer></>}</Sheet>;
}
