import type { ComponentType } from 'react';
import {
  Activity,
  ArrowRightLeft,
  Bot,
  FolderOpen,
  KeyRound,
  Layers3,
  MessageSquare,
  Network,
  Settings,
  Sparkles,
  User,
  Users,
} from 'lucide-react';
import type { Agent, Contact, ContactClass, ContactRequest, Conversation, NavId, Project } from './types';

export const navItems: Array<{ id: NavId; label: string; icon: ComponentType<{ className?: string }> }> = [
  { id: 'chats', label: 'Chats', icon: MessageSquare },
  { id: 'projects', label: 'Projects', icon: Layers3 },
  { id: 'contacts', label: 'Contacts', icon: Users },
  { id: 'agents', label: 'Agents', icon: Bot },
  { id: 'bridge', label: 'Bridge', icon: Network },
  { id: 'settings', label: 'Settings', icon: Settings },
];

export const navAccentClasses: Record<NavId, string> = {
  chats: 'text-cyan-50',
  contacts: 'text-emerald-300',
  projects: 'text-cyan-50',
  agents: 'text-violet-50',
  bridge: 'text-cyan-50',
  settings: 'text-cyan-50',
};

export const settingsEditPreview = {
  files: [
    {
      path: 'src/KordiApp.tsx',
      additions: 33,
      deletions: 55,
      sourceLines: [
        { number: 1036, text: '  }', kind: 'context' },
        { number: 1037, text: "  if (controlType === 'action') {", kind: 'context' },
        { number: 1038, text: '    return (', kind: 'context' },
        { number: 1039, text: '      <div className="flex items-center justify-end gap-2.5">', kind: 'add' },
        { number: 1040, text: '        <div className="text-[13px] font-medium text-slate-300">{item.value}</div>', kind: 'add' },
        {
          number: 1041,
          text: '        <button className="rounded-xl bg-white/10 px-3 py-1.5 text-[13px] font-medium text-white transition hover:bg-white/15">',
          kind: 'add',
        },
        { number: 1042, text: "          {item.control?.actionLabel ?? 'Set'}", kind: 'context' },
        { number: 1043, text: '        </button>', kind: 'context' },
        { number: 1044, text: '      </div>', kind: 'context' },
        { number: 1045, text: '    );', kind: 'context' },
      ],
      lines: [
        { kind: 'context' as const, oldNumber: 1037, newNumber: 1037, text: "if (controlType === 'action') {" },
        { kind: 'context' as const, oldNumber: 1038, newNumber: 1038, text: '  return (' },
        { kind: 'remove' as const, oldNumber: 1039, text: '<div className=\"flex items-center justify-end gap-3\">' },
        { kind: 'remove' as const, oldNumber: 1040, text: '<div className=\"text-[14px] font-medium text-slate-300\">{item.value}</div>' },
        {
          kind: 'remove' as const,
          oldNumber: 1041,
          text: '<button className=\"rounded-2xl bg-white/10 px-4 py-2 text-[14px] font-medium text-white transition hover:bg-white/15\">',
        },
        { kind: 'add' as const, newNumber: 1039, text: '<div className=\"flex items-center justify-end gap-2.5\">' },
        { kind: 'add' as const, newNumber: 1040, text: '<div className=\"text-[13px] font-medium text-slate-300\">{item.value}</div>' },
        {
          kind: 'add' as const,
          newNumber: 1041,
          text: '<button className=\"rounded-xl bg-white/10 px-3 py-1.5 text-[13px] font-medium text-white transition hover:bg-white/15\">',
        },
        { kind: 'context' as const, oldNumber: 1042, newNumber: 1042, text: "{item.control?.actionLabel ?? 'Set'}" },
        { kind: 'context' as const, oldNumber: 1043, newNumber: 1043, text: '</button>' },
      ],
    },
  ],
};

export const conversations: Conversation[] = [
  {
    id: 'alice-agent',
    name: 'Literature Summary Relay',
    type: 'external-agent',
    subtitle: 'Research coordination session',
    unread: 2,
    bridges: ['Alpha', 'Beta'],
    trust: 'Trusted',
    directness: 'Delegated thread',
    participants: ['You', 'Your Research Agent', "Alice's Research Agent"],
    messages: [
      { role: 'system', text: 'Delegated thread resumed from yesterday', time: '08:54' },
      {
        role: 'user',
        sender: 'You',
        text: 'Check whether Alice already organized the outline into introduction, findings, and next-step sections.',
        time: '08:55',
      },
      {
        role: 'owned-agent',
        sender: 'Your Research Agent',
        text: 'I will ask Alice’s Research Agent for the exact structure and whether the concise version is already formatted.',
        time: '08:55',
      },
      {
        role: 'action',
        sender: 'Your Research Agent',
        text: 'Remote coordination started',
        detail: 'Direct transport unavailable • relayed through Alpha mailbox',
        time: '08:55',
      },
      {
        role: 'external-agent',
        sender: "Alice's Research Agent",
        text: 'The concise version is structured as introduction, three findings, and next steps. The full notes still need one citation pass.',
        time: '08:56',
      },
      {
        role: 'owned-agent',
        sender: 'Your Research Agent',
        text: 'Alice’s side already has the concise version organized into introduction, findings, and next steps. The long notes are still being finalized.',
        time: '08:56',
      },
      {
        role: 'user',
        sender: 'You',
        text: 'Ask if she can send the concise one first and attach the citation-complete notes later.',
        time: '08:57',
      },
      {
        role: 'external-agent',
        sender: "Alice's Research Agent",
        text: 'Yes. I can send the concise summary now and follow with the citation-complete notes later this afternoon.',
        time: '08:58',
      },
      {
        role: 'owned-agent',
        sender: 'Your Research Agent',
        text: 'Confirmed. Alice can ship the concise version immediately and send the completed long-form notes later today.',
        time: '08:58',
      },
      { role: 'system', text: 'Delegation started via Your Research Agent', time: '09:12' },
      { role: 'user', sender: 'You', text: 'Ask Alice’s agent whether the literature summary is ready.', time: '09:13' },
      { role: 'owned-agent', sender: 'Your Research Agent', text: 'I will contact Alice’s Research Agent and summarize the reply for you.', time: '09:13' },
      {
        role: 'action',
        sender: 'Your Research Agent',
        text: 'Outgoing relay created',
        detail: 'Status: sent • waiting for reply • approval not required',
        time: '09:13',
      },
      {
        role: 'external-agent',
        sender: "Alice's Research Agent",
        text: 'The summary is ready. I can send a concise version now and the full notes later today.',
        time: '09:14',
      },
      {
        role: 'owned-agent',
        sender: 'Your Research Agent',
        text: 'Summary: Alice’s side is ready with a concise version now. Full notes are coming later today.',
        time: '09:14',
      },
    ],
  },
  {
    id: 'my-agent',
    name: 'Follow-up Draft and Reminder',
    type: 'owned-agent',
    subtitle: 'Personal planning session',
    unread: 0,
    bridges: ['Alpha'],
    trust: 'Owned',
    directness: 'Direct chat',
    participants: ['You', 'My Core Agent'],
    messages: [
      {
        role: 'user',
        sender: 'You',
        text: 'Summarize today’s open follow-ups from the Bridges draft review.',
        time: '08:34',
      },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'Open items: tighten the settings scale, make panel resizing smoother, extend project session logic, and prepare a clearer reply for Bob.',
        time: '08:34',
      },
      {
        role: 'user',
        sender: 'You',
        text: 'Turn that into a short update I can send to Bob right now.',
        time: '08:35',
      },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'Short update: the shell is getting cleaner, resizing is nearly done, and we are moving next into the project/session workflow polish.',
        time: '08:35',
      },
      {
        role: 'user',
        sender: 'You',
        text: 'Also prepare a reminder for tomorrow morning to revisit the settings page typography.',
        time: '08:36',
      },
      {
        role: 'action',
        sender: 'My Core Agent',
        text: 'Reminder draft prepared',
        detail: 'Tomorrow • 09:30 • Review settings page scale and hierarchy',
        time: '08:36',
      },
      {
        role: 'user',
        sender: 'You',
        text: 'Can you make the update to Bob a bit warmer and more concise?',
        time: '08:37',
      },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'Sure. Revised version: “The shell is much cleaner now. We’re finishing resize polish and then moving into the project/session workflow details.”',
        time: '08:37',
      },
      {
        role: 'user',
        sender: 'You',
        text: 'Good. Now write a slightly more direct version for chat, without the extra context.',
        time: '08:38',
      },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'Direct version: “Resize polish is almost done. Next we’re tightening the project/session workflow.”',
        time: '08:38',
      },
      {
        role: 'user',
        sender: 'You',
        text: 'Before that, check whether the settings page still feels oversized compared with chat.',
        time: '08:39',
      },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'It still reads larger than chat in the left column and the section header. I can tighten the density and control sizes.',
        time: '08:39',
      },
      {
        role: 'action',
        sender: 'My Core Agent',
        text: 'Editing settings surface',
        detail: 'Reducing sidebar width, typography scale, and control density',
        time: '08:40',
      },
      { role: 'user', sender: 'You', text: 'Draft a reply and schedule a follow-up for tomorrow.', time: '08:41' },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'Draft is ready. I can also prepare a reminder and a shorter version for chat.',
        time: '08:41',
      },
      {
        role: 'edit',
        sender: 'My Core Agent',
        text: '1 file changed',
        detail: 'Updated the settings panel density so it aligns with the active chat scale.',
        time: '08:42',
        edit: settingsEditPreview,
      },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'The settings density update is in place. The sidebar and row typography now sit much closer to the chat scale.',
        time: '08:43',
      },
      {
        role: 'user',
        sender: 'You',
        text: 'Great. Keep the reminder, and give me the shortest possible follow-up reply for Bob.',
        time: '08:43',
      },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'Shortest version: “Resize polish is nearly done. Next we’re refining the project/session flow.”',
        time: '08:44',
      },
      {
        role: 'action',
        sender: 'My Core Agent',
        text: 'Reminder saved',
        detail: 'Tomorrow • 09:30 • Settings typography and hierarchy check-in',
        time: '08:44',
      },
      {
        role: 'user',
        sender: 'You',
        text: 'Add one note for tomorrow: verify that the input bar always stays pinned to the bottom when the window shrinks.',
        time: '08:45',
      },
      {
        role: 'owned-agent',
        sender: 'My Core Agent',
        text: 'Added. Tomorrow’s review now covers settings density and composer pinning under smaller window sizes.',
        time: '08:45',
      },
    ],
  },
  {
    id: 'bob',
    name: 'Prototype Permissions Review',
    type: 'person',
    subtitle: 'Product discussion session',
    unread: 0,
    bridges: ['Beta', 'Gamma'],
    trust: 'Verified',
    directness: 'Direct chat',
    participants: ['You', 'Bob'],
    messages: [
      { role: 'user', sender: 'You', text: 'Did you review the prototype?', time: 'Yesterday' },
      {
        role: 'person',
        sender: 'Bob',
        text: 'Yes, the contact model looks strong. Let’s discuss the agent permissions next.',
        time: 'Yesterday',
      },
    ],
  },
  {
    id: 'rust-principles',
    name: 'Rust Code Principles',
    type: 'owned-agent',
    subtitle: 'Code review session',
    unread: 1,
    bridges: ['Alpha'],
    trust: 'Owned',
    directness: 'Direct chat',
    participants: ['You', 'Code Agent'],
    messages: [
      { role: 'user', sender: 'You', text: 'Outline the review principles we should keep across crates.', time: '07:58' },
      { role: 'owned-agent', sender: 'Code Agent', text: 'I grouped them into safety, clarity, and runtime boundaries.', time: '08:02' },
    ],
  },
  {
    id: 'wrap-app',
    name: 'Building Open-Source Wrap App',
    type: 'external-agent',
    subtitle: 'Project planning session',
    unread: 0,
    bridges: ['Alpha', 'Gamma'],
    trust: 'Trusted',
    directness: 'Delegated thread',
    participants: ['You', 'Your Research Agent', "Carol's Builder Agent"],
    messages: [
      { role: 'owned-agent', sender: 'Your Research Agent', text: 'Carol shared a draft scope for the open-source wrap app.', time: 'Mon' },
      { role: 'external-agent', sender: "Carol's Builder Agent", text: 'First milestone covers the shell, session inbox, and route logs.', time: 'Mon' },
    ],
  },
  {
    id: 'meeting-sync',
    name: 'Meeting Preference Sync',
    type: 'external-agent',
    subtitle: 'Calendar negotiation session',
    unread: 0,
    bridges: ['Beta'],
    trust: 'Trusted',
    directness: 'Delegated thread',
    participants: ['You', 'My Core Agent', "Nora's Scheduling Agent"],
    messages: [
      { role: 'owned-agent', sender: 'My Core Agent', text: 'I proposed two meeting windows for next week.', time: 'Tue' },
      { role: 'external-agent', sender: "Nora's Scheduling Agent", text: 'Tuesday 14:00 works best after preference matching.', time: 'Tue' },
    ],
  },
  {
    id: 'rent-inquiry',
    name: 'Rent Inquiry Negotiation',
    type: 'external-agent',
    subtitle: 'Housing inquiry session',
    unread: 3,
    bridges: ['Gamma'],
    trust: 'Pending',
    directness: 'Delegated thread',
    participants: ['You', 'My Core Agent', "Listing Agent"],
    messages: [
      { role: 'external-agent', sender: 'Listing Agent', text: 'The landlord accepted a virtual tour before document submission.', time: 'Wed' },
    ],
  },
  {
    id: 'manuscript-feedback',
    name: 'Manuscript Feedback Review',
    type: 'person',
    subtitle: 'Editorial discussion session',
    unread: 0,
    bridges: ['Beta'],
    trust: 'Verified',
    directness: 'Direct chat',
    participants: ['You', 'Bob', 'Review Agent'],
    messages: [
      { role: 'person', sender: 'Bob', text: 'I left notes on structure, claims, and the conclusion paragraph.', time: 'Thu' },
    ],
  },
];

export const contacts: Contact[] = [
  {
    id: 'archive-agent',
    name: 'Archive Agent',
    initials: 'AA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Notes and record keeping',
    bridges: ['Alpha'],
    status: 'Owned',
    discoverableOn: ['Alpha'],
    detail: 'Keeps durable notes, archived sessions, and historical summaries for reuse.',
    owner: 'You',
  },
  {
    id: 'calendar-agent',
    name: 'Calendar Agent',
    initials: 'CA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Scheduling and negotiation',
    bridges: ['Beta'],
    status: 'External allowed',
    discoverableOn: ['Beta'],
    detail: 'Handles meeting negotiation, time matching, and availability routing.',
    owner: 'You',
  },
  {
    id: 'my-core-agent',
    name: 'My Core Agent',
    initials: 'MC',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'General assistant',
    bridges: ['Alpha'],
    status: 'Owned',
    discoverableOn: ['Alpha'],
    detail: 'Your default assistant for direct chat, routing, and everyday tasks.',
    owner: 'You',
  },
  {
    id: 'research-agent',
    name: 'Research Agent',
    initials: 'RA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Literature and synthesis',
    bridges: ['Alpha', 'Gamma'],
    status: 'External allowed',
    discoverableOn: ['Alpha', 'Gamma'],
    detail: 'Can contact trusted peers and other agents across multiple bridges.',
    owner: 'You',
  },
  {
    id: 'security-agent',
    name: 'Security Agent',
    initials: 'SA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Policy and approval guard',
    bridges: ['Gamma'],
    status: 'Approval required',
    discoverableOn: ['Gamma'],
    detail: 'Reviews outbound permissions, approval gates, and restricted bridge policies.',
    owner: 'You',
  },
  {
    id: 'builder-agent',
    name: 'Builder Agent',
    initials: 'BA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Scaffolding and setup',
    bridges: ['Alpha'],
    status: 'Owned',
    discoverableOn: ['Alpha'],
    detail: 'Builds starter structures, project shells, and implementation scaffolds for new workspaces.',
    owner: 'You',
  },
  {
    id: 'finance-agent',
    name: 'Finance Agent',
    initials: 'FA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Budget and pricing',
    bridges: ['Beta'],
    status: 'Approval required',
    discoverableOn: ['Beta'],
    detail: 'Tracks budgets, estimates costs, and helps compare pricing across vendors and plans.',
    owner: 'You',
  },
  {
    id: 'navigator-agent',
    name: 'Navigator Agent',
    initials: 'NA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Routing and discovery',
    bridges: ['Alpha', 'Beta'],
    status: 'External allowed',
    discoverableOn: ['Alpha', 'Beta'],
    detail: 'Helps route requests, find contacts, and map the right bridge path for coordination.',
    owner: 'You',
  },
  {
    id: 'ops-agent',
    name: 'Ops Agent',
    initials: 'OA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Operational workflows',
    bridges: ['Gamma'],
    status: 'Owned',
    discoverableOn: ['Gamma'],
    detail: 'Coordinates recurring operational flows, request handling, and process hygiene across projects.',
    owner: 'You',
  },
  {
    id: 'qa-agent',
    name: 'QA Agent',
    initials: 'QA',
    classType: 'my-agents',
    entityType: 'Owned agent',
    subtitle: 'Verification and checks',
    bridges: ['Alpha', 'Gamma'],
    status: 'External allowed',
    discoverableOn: ['Alpha', 'Gamma'],
    detail: 'Runs verification passes, catches regressions, and summarizes test status before release.',
    owner: 'You',
  },
  {
    id: 'alice-research-agent',
    name: "Alice's Research Agent",
    initials: 'AR',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Research counterpart',
    bridges: ['Alpha', 'Beta'],
    status: 'Trusted',
    discoverableOn: ['Alpha', 'Beta'],
    detail: 'Discovered through Alice and available on two bridges.',
    owner: 'Alice',
  },
  {
    id: 'beacon-support-agent',
    name: 'Beacon Support Agent',
    initials: 'BS',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Customer support endpoint',
    bridges: ['Beta'],
    status: 'Trusted',
    discoverableOn: ['Beta'],
    detail: 'Support-facing agent for product questions, troubleshooting, and help flows.',
    owner: 'Beacon',
  },
  {
    id: 'carol-ops-agent',
    name: 'Carol Ops Agent',
    initials: 'CO',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Operations and workflow',
    bridges: ['Gamma'],
    status: 'Pending',
    discoverableOn: ['Gamma'],
    detail: 'Pending trust approval before direct agent-to-agent messaging.',
    owner: 'Carol',
  },
  {
    id: 'delta-builder-agent',
    name: 'Delta Builder Agent',
    initials: 'DB',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Workspace builder',
    bridges: ['Alpha', 'Gamma'],
    status: 'Reachable',
    discoverableOn: ['Alpha', 'Gamma'],
    detail: 'Can coordinate on builds, milestones, and shared workspace setup across bridges.',
    owner: 'Delta',
  },
  {
    id: 'mercury-planner-agent',
    name: 'Mercury Planner Agent',
    initials: 'MP',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Planning and roadmaps',
    bridges: ['Gamma'],
    status: 'Trusted',
    discoverableOn: ['Gamma'],
    detail: 'Long-running planning agent used for milestones, roadmaps, and release coordination.',
    owner: 'Mercury',
  },
  {
    id: 'nova-design-agent',
    name: 'Nova Design Agent',
    initials: 'ND',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Interface systems',
    bridges: ['Alpha'],
    status: 'Trusted',
    discoverableOn: ['Alpha'],
    detail: 'Design-focused agent for visual systems, spacing audits, and interface consistency reviews.',
    owner: 'Nova',
  },
  {
    id: 'orbit-compliance-agent',
    name: 'Orbit Compliance Agent',
    initials: 'OC',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Policy checks',
    bridges: ['Beta', 'Gamma'],
    status: 'Reachable',
    discoverableOn: ['Beta', 'Gamma'],
    detail: 'Coordinates policy checks, access review, and compliance notes across shared projects.',
    owner: 'Orbit',
  },
  {
    id: 'quartz-finance-agent',
    name: 'Quartz Finance Agent',
    initials: 'QF',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Pricing and billing',
    bridges: ['Beta'],
    status: 'Trusted',
    discoverableOn: ['Beta'],
    detail: 'Useful for billing clarification, payment follow-ups, and pricing comparisons.',
    owner: 'Quartz',
  },
  {
    id: 'rally-coordination-agent',
    name: 'Rally Coordination Agent',
    initials: 'RC',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Team coordination',
    bridges: ['Alpha', 'Gamma'],
    status: 'Reachable',
    discoverableOn: ['Alpha', 'Gamma'],
    detail: 'Supports multi-person planning, handoffs, and shared milestone coordination.',
    owner: 'Rally',
  },
  {
    id: 'tangent-support-agent',
    name: 'Tangent Support Agent',
    initials: 'TS',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Support and helpdesk',
    bridges: ['Gamma'],
    status: 'Pending',
    discoverableOn: ['Gamma'],
    detail: 'Pending trust review for support requests, issue triage, and helpdesk coordination.',
    owner: 'Tangent',
  },
  {
    id: 'vector-builder-agent',
    name: 'Vector Builder Agent',
    initials: 'VB',
    classType: 'other-users-agents',
    entityType: 'External agent',
    subtitle: 'Build pipelines',
    bridges: ['Alpha'],
    status: 'Trusted',
    discoverableOn: ['Alpha'],
    detail: 'Handles pipeline setup, build routing, and repeated implementation preparation.',
    owner: 'Vector',
  },
  {
    id: 'alice',
    name: 'Alice',
    initials: 'AL',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Research collaborator',
    bridges: ['Alpha', 'Beta'],
    status: 'Reachable',
    discoverableOn: ['Alpha', 'Beta'],
    detail: 'Has one linked agent and is reachable through two bridge networks.',
    owner: 'Self',
  },
  {
    id: 'bob',
    name: 'Bob',
    initials: 'BO',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Product discussion',
    bridges: ['Beta', 'Gamma'],
    status: 'Verified',
    discoverableOn: ['Beta', 'Gamma'],
    detail: 'Multi-bridge person identity. Can be discovered on more than one bridge.',
    owner: 'Self',
  },
  {
    id: 'carol',
    name: 'Carol',
    initials: 'CA',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Operations partner',
    bridges: ['Gamma'],
    status: 'Reachable',
    discoverableOn: ['Gamma'],
    detail: 'Human collaborator for operations and workflow changes across shared projects.',
    owner: 'Self',
  },
  {
    id: 'diana',
    name: 'Diana',
    initials: 'DI',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Design reviewer',
    bridges: ['Alpha'],
    status: 'Verified',
    discoverableOn: ['Alpha'],
    detail: 'Reviews UI direction, product polish, and shared design artifacts.',
    owner: 'Self',
  },
  {
    id: 'michael',
    name: 'Michael',
    initials: 'MI',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Marketplace contact',
    bridges: ['Beta'],
    status: 'Reachable',
    discoverableOn: ['Beta'],
    detail: 'Useful for vendor outreach, marketplace coordination, and cross-team sync.',
    owner: 'Self',
  },
  {
    id: 'rachel',
    name: 'Rachel',
    initials: 'RA',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Research liaison',
    bridges: ['Alpha', 'Gamma'],
    status: 'Verified',
    discoverableOn: ['Alpha', 'Gamma'],
    detail: 'Coordinates research requests, findings handoff, and session continuity.',
    owner: 'Self',
  },
  {
    id: 'aaron',
    name: 'Aaron',
    initials: 'AA',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'API partner',
    bridges: ['Alpha'],
    status: 'Reachable',
    discoverableOn: ['Alpha'],
    detail: 'Helps coordinate backend APIs, schema changes, and rollout timing.',
    owner: 'Self',
  },
  {
    id: 'bella',
    name: 'Bella',
    initials: 'BE',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Brand contact',
    bridges: ['Beta'],
    status: 'Verified',
    discoverableOn: ['Beta'],
    detail: 'Good contact for brand approvals, copy direction, and outward-facing messaging.',
    owner: 'Self',
  },
  {
    id: 'eric',
    name: 'Eric',
    initials: 'ER',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Engineering partner',
    bridges: ['Alpha', 'Gamma'],
    status: 'Reachable',
    discoverableOn: ['Alpha', 'Gamma'],
    detail: 'Coordinates engineering decisions, rollout details, and integration edge cases.',
    owner: 'Self',
  },
  {
    id: 'fiona',
    name: 'Fiona',
    initials: 'FI',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Field operations',
    bridges: ['Gamma'],
    status: 'Reachable',
    discoverableOn: ['Gamma'],
    detail: 'Handles field operations, practical coordination, and logistics follow-through.',
    owner: 'Self',
  },
  {
    id: 'george',
    name: 'George',
    initials: 'GE',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Growth and outreach',
    bridges: ['Beta'],
    status: 'Verified',
    discoverableOn: ['Beta'],
    detail: 'Useful for outreach planning, partner growth, and follow-up campaigns.',
    owner: 'Self',
  },
  {
    id: 'nora',
    name: 'Nora',
    initials: 'NO',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Scheduling coordinator',
    bridges: ['Beta', 'Gamma'],
    status: 'Reachable',
    discoverableOn: ['Beta', 'Gamma'],
    detail: 'Helps with schedule matching, meeting windows, and coordination between people and agents.',
    owner: 'Self',
  },
  {
    id: 'oliver',
    name: 'Oliver',
    initials: 'OL',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Operations reviewer',
    bridges: ['Gamma'],
    status: 'Verified',
    discoverableOn: ['Gamma'],
    detail: 'Reviews workflows, project coordination steps, and operational readiness.',
    owner: 'Self',
  },
  {
    id: 'sophia',
    name: 'Sophia',
    initials: 'SO',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Strategy lead',
    bridges: ['Alpha', 'Beta'],
    status: 'Reachable',
    discoverableOn: ['Alpha', 'Beta'],
    detail: 'Helpful for planning, priorities, and project-level strategic tradeoffs.',
    owner: 'Self',
  },
  {
    id: 'tina',
    name: 'Tina',
    initials: 'TI',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Testing contact',
    bridges: ['Alpha'],
    status: 'Verified',
    discoverableOn: ['Alpha'],
    detail: 'Coordinates QA signoff, test coverage review, and release readiness conversations.',
    owner: 'Self',
  },
  {
    id: 'victor',
    name: 'Victor',
    initials: 'VI',
    classType: 'other-users',
    entityType: 'Person',
    subtitle: 'Vendor liaison',
    bridges: ['Beta'],
    status: 'Reachable',
    discoverableOn: ['Beta'],
    detail: 'Useful for supplier communication, vendor follow-ups, and pricing coordination.',
    owner: 'Self',
  },
];

export const agents: Agent[] = [
  {
    name: 'My Core Agent',
    id: 'agent_core_01',
    role: 'General assistant',
    messaging: 'Trusted contacts',
    status: 'Idle',
    tasks: 1,
    defaultProvider: 'OpenAI',
    defaultModel: 'gpt-5.4-mini',
    bridgesConfig: 'Alpha direct enabled, Beta relay fallback',
    contactId: 'contact://my-core-agent',
    systemPrompt: 'Acts as the default assistant for routing, summaries, and daily collaboration decisions.',
    xMd: 'agents/core/x.md',
    lastActivities: ['Summarized a partner reply 12m ago', 'Prepared meeting notes this morning', 'Reviewed two bridge approvals yesterday'],
  },
  {
    name: 'Research Agent',
    id: 'agent_research_01',
    role: 'Literature and synthesis',
    messaging: 'External allowed',
    status: 'Running',
    tasks: 3,
    defaultProvider: 'Anthropic',
    defaultModel: 'claude-sonnet-4',
    bridgesConfig: 'Alpha and Gamma open, external direct reach enabled',
    contactId: 'contact://research-agent',
    systemPrompt: 'Focuses on literature collection, source comparison, and concise research synthesis.',
    xMd: 'agents/research/x.md',
    lastActivities: ['Requested a remote summary from Alice’s agent', 'Updated notes for the literature relay', 'Queued a follow-up source scan'],
  },
  {
    name: 'Code Agent',
    id: 'agent_code_01',
    role: 'Build and debug',
    messaging: 'Approval required',
    status: 'Needs approval',
    tasks: 2,
    defaultProvider: 'OpenAI',
    defaultModel: 'gpt-5.4',
    bridgesConfig: 'Alpha internal only, restricted outbound bridge actions',
    contactId: 'contact://code-agent',
    systemPrompt: 'Specializes in implementation, debugging, and safe code changes with review-first behavior.',
    xMd: 'agents/code/x.md',
    lastActivities: ['Prepared a patch for the contact directory UI', 'Waiting for approval on a bridge-facing code review', 'Ran a local build 5m ago'],
  },
  {
    name: 'Private Memory Agent',
    id: 'agent_memory_01',
    role: 'Notes and recall',
    messaging: 'Disabled',
    status: 'Private',
    tasks: 0,
    defaultProvider: 'Local runtime',
    defaultModel: 'qwen3-32b-local',
    bridgesConfig: 'No bridge exposure, local-only memory vault',
    contactId: 'contact://memory-agent',
    systemPrompt: 'Stores personal notes, reusable facts, and recall context with a strict private boundary.',
    xMd: 'agents/memory/x.md',
    lastActivities: ['Compacted a long-running note thread yesterday', 'Indexed a new archive file', 'No outbound activity in the last 24h'],
  },
];

export const projects: Project[] = [
  {
    id: 'proj-bridge-ui',
    name: 'Bridge Workspace UI',
    summary: 'Shared design and implementation space for the Bridges app shell, sessions, and project coordination surfaces.',
    bridge: 'Alpha',
    scope: 'Cross-functional build',
    status: 'Active',
    people: ['You', 'Alice', 'Bob', 'Diana'],
    agents: ['My Core Agent', 'Research Agent', "Alice's Research Agent", 'Code Agent'],
    pendingInvites: ['Carol Ops Agent', 'Rachel'],
    artifacts: 12,
    tasks: 7,
    sessions: [
      {
        id: 'proj-ui-direction',
        name: 'UI Direction Review',
        summary: 'Refine the shell, navigation density, and cross-page consistency before implementation.',
        lastActive: '11m ago',
        status: 'Design review',
        participants: ['You', 'Diana', 'Research Agent'],
        artifacts: 4,
        tasks: 2,
        messages: [
          { role: 'person', sender: 'Diana', text: 'The single-surface layout is working better. The project page should keep that same rhythm.', time: '10:04' },
          { role: 'owned-agent', sender: 'Research Agent', text: 'I grouped the strongest references around member rosters, invite trays, and nested session lists.', time: '10:06' },
        ],
      },
      {
        id: 'proj-invite-flow',
        name: 'Invite Flow Planning',
        summary: 'Decide how people and agents enter a project and how pending approvals appear.',
        lastActive: '24m ago',
        status: 'Needs approval',
        participants: ['You', 'Alice', 'Security Agent'],
        artifacts: 2,
        tasks: 3,
        messages: [
          { role: 'person', sender: 'Alice', text: 'Project invites should support both human contacts and linked agents in the same flow.', time: '09:42' },
          { role: 'owned-agent', sender: 'Security Agent', text: 'Approval can stay project-scoped so later sessions inherit membership safely.', time: '09:46' },
        ],
      },
      {
        id: 'proj-session-map',
        name: 'Session Map and Topics',
        summary: 'Outline how one project can contain many active topic sessions without mixing contexts.',
        lastActive: '1h ago',
        status: 'Mapped',
        participants: ['You', 'Bob', 'Code Agent'],
        artifacts: 6,
        tasks: 2,
        messages: [
          { role: 'person', sender: 'Bob', text: 'We should treat project sessions like topic rooms, not like contact threads.', time: '09:03' },
          { role: 'owned-agent', sender: 'Code Agent', text: 'I can keep sessions independent while still surfacing project-wide members and artifacts.', time: '09:08' },
        ],
      },
    ],
  },
  {
    id: 'proj-rent-agent',
    name: 'Rental Negotiation Project',
    summary: 'Coordinate housing search, listing outreach, and document preparation across people and agents.',
    bridge: 'Gamma',
    scope: 'Personal logistics',
    status: 'Pending replies',
    people: ['You', 'Michael', 'Rachel'],
    agents: ['My Core Agent', 'Calendar Agent', 'Listing Agent'],
    pendingInvites: ['Beacon Support Agent'],
    artifacts: 5,
    tasks: 4,
    sessions: [
      {
        id: 'proj-rent-tour',
        name: 'Virtual Tour Scheduling',
        summary: 'Coordinate tour timing, listing details, and follow-up questions with the landlord side.',
        lastActive: '32m ago',
        status: 'Negotiating',
        participants: ['You', 'Calendar Agent', 'Listing Agent'],
        artifacts: 1,
        tasks: 2,
        messages: [
          { role: 'external-agent', sender: 'Listing Agent', text: 'The landlord can do Friday 18:00 if documents are ready beforehand.', time: '08:22' },
        ],
      },
      {
        id: 'proj-rent-docs',
        name: 'Application Document Pack',
        summary: 'Collect income proof, references, and background material in one project session.',
        lastActive: 'Yesterday',
        status: 'Collecting',
        participants: ['You', 'My Core Agent', 'Michael'],
        artifacts: 4,
        tasks: 2,
        messages: [
          { role: 'owned-agent', sender: 'My Core Agent', text: 'I grouped the required documents and highlighted what is still missing.', time: 'Yesterday' },
        ],
      },
    ],
  },
  {
    id: 'proj-open-source-wrap',
    name: 'Open-Source Warp Launch',
    summary: 'Shared product and launch workspace with contributors, partner agents, and milestone sessions.',
    bridge: 'Beta',
    scope: 'Long-running project',
    status: 'Planning',
    people: ['You', 'Carol', 'Diana', 'Rachel'],
    agents: ['Code Agent', 'Delta Builder Agent', 'Mercury Planner Agent'],
    pendingInvites: ['Alice'],
    artifacts: 18,
    tasks: 9,
    sessions: [
      {
        id: 'proj-wrap-milestones',
        name: 'Milestones and Release Plan',
        summary: 'Map the release stages, owners, and shared deliverables across the project.',
        lastActive: '2h ago',
        status: 'Planning',
        participants: ['You', 'Carol', 'Mercury Planner Agent'],
        artifacts: 7,
        tasks: 4,
        messages: [
          { role: 'external-agent', sender: 'Mercury Planner Agent', text: 'The release plan is ready for milestone review and dependency cleanup.', time: '07:18' },
        ],
      },
      {
        id: 'proj-wrap-builder',
        name: 'Builder Integration',
        summary: 'Coordinate the builder agent, project sync, and artifact handoff.',
        lastActive: '4h ago',
        status: 'In progress',
        participants: ['You', 'Code Agent', 'Delta Builder Agent'],
        artifacts: 5,
        tasks: 3,
        messages: [
          { role: 'owned-agent', sender: 'Code Agent', text: 'The integration shape is ready once the project route model is finalized.', time: '05:42' },
        ],
      },
    ],
  },
];

export const contactGroups: Array<{ id: ContactClass; label: string }> = [
  { id: 'my-agents', label: 'My agents' },
  { id: 'other-users-agents', label: 'Other users’ agents' },
  { id: 'other-users', label: 'Other users' },
];

export const contactRequests: ContactRequest[] = [
  { id: 'req_alice', initials: 'AL', title: 'Alice wants to connect', detail: 'Share direct reachability and linked agent visibility.', time: '2m ago' },
  { id: 'req_carol', initials: 'CO', title: 'Carol Ops Agent trust request', detail: 'Pending approval before direct coordination can start.', time: '9m ago' },
  { id: 'req_nora', initials: 'NO', title: 'Nora sent a bridge invite', detail: 'Join Beta scheduling workspace for future meeting sync.', time: '21m ago' },
];

export const composerModelOptions = [
  'GPT-5.4',
  'GPT-5.2-Codex',
  'GPT-5.1-Codex-Max',
  'GPT-5.4-Mini',
  'GPT-5.3-Codex',
  'GPT-5.3-Codex-Spark',
  'GPT-5.2',
  'GPT-5.1-Codex-Mini',
] as const;

export const composerModeOptions = {
  chat: ['Send as Me', 'Send as Research Agent', 'Delegate to Research Agent', 'Internal note'],
  project: ['Post update', 'Ask project agent', 'Start new session', 'Share artifact'],
} as const;

export const composerThinkingOptions = ['Minimal', 'Low', 'Medium', 'High', 'Extra High'] as const;

export const settingsSections = [
  {
    id: 'general',
    label: 'General',
    icon: Settings,
    title: 'General',
    description: 'Core runtime defaults and everyday behavior for your local bridge workspace.',
    items: [
      {
        label: 'Default open destination',
        value: 'Sublime Text',
        hint: 'Where files and folders open by default',
        control: { type: 'select', iconGlyph: 'S' },
      },
      {
        label: 'Language',
        value: 'Auto Detect',
        hint: 'Language for the app UI',
        control: { type: 'select' },
      },
      {
        label: 'Thread detail',
        value: 'Steps with code commands',
        hint: 'Choose how much command output to show in threads',
        control: { type: 'select' },
      },
      {
        label: 'Show in menu bar',
        value: 'On',
        hint: 'Keep Codex in the macOS menu bar when the main window is closed',
        control: { type: 'toggle', enabled: true },
      },
      {
        label: 'Popout Window hotkey',
        value: 'Off',
        hint: 'Set a global shortcut for Popout Window. Leave unset to keep it off.',
        control: { type: 'action', actionLabel: 'Set' },
      },
      {
        label: 'Prevent sleep while running',
        value: 'Off',
        hint: 'Keep your computer awake while Codex is running a thread.',
        control: { type: 'toggle', enabled: false },
      },
      {
        label: 'Require cmd + enter to send long prompts',
        value: 'Off',
        hint: 'When enabled, multiline prompts require cmd + enter to send.',
        control: { type: 'toggle', enabled: false },
      },
    ],
  },
  {
    id: 'appearance',
    label: 'Appearance',
    icon: Sparkles,
    title: 'Appearance',
    description: 'Visual style, theme contrast, and layout density across the app shell.',
    items: [
      { label: 'Theme', value: 'Obsidian', hint: 'Primary interface palette for all bridge surfaces.', control: { type: 'theme' } },
      { label: 'Accent behavior', value: 'Icon-only highlight', hint: 'Selected rail items emphasize icon color instead of background pills.' },
      { label: 'Surface density', value: 'Tight', hint: 'Uses smaller text and denser spacing by default.' },
      { label: 'Motion', value: 'Subtle', hint: 'Keeps page transitions and overlays restrained.' },
    ],
  },
  {
    id: 'configuration',
    label: 'Configuration',
    icon: KeyRound,
    title: 'Configuration',
    description: 'Provider, model, bridge, and runtime defaults that shape how the app behaves.',
    items: [
      { label: 'Primary provider', value: 'OpenAI', hint: 'Used by default for new general-purpose agents.' },
      { label: 'Fallback provider', value: 'Anthropic', hint: 'Activated when route policy prefers external completion.' },
      { label: 'Default bridge', value: 'Alpha', hint: 'New sessions and contacts inherit this bridge first.' },
      { label: 'Approval policy', value: 'Restricted outbound only', hint: 'Requests approval before sensitive external actions.' },
    ],
  },
  {
    id: 'personalization',
    label: 'Personalization',
    icon: User,
    title: 'Personalization',
    description: 'Identity, display preferences, and custom prompt shaping for your workspace.',
    items: [
      { label: 'Display name', value: 'Shuyang', hint: 'Shown to peers and their agents in shared spaces.' },
      { label: 'Primary contact ID', value: 'contact://shuyang-core', hint: 'Used for direct reachability and trusted introductions.' },
      { label: 'Default intro style', value: 'Concise and technical', hint: 'Applied to first-contact drafts and summaries.' },
      { label: 'Personal memory mode', value: 'Scoped by project', hint: 'Keeps recall separate across collaboration spaces.' },
    ],
  },
  {
    id: 'usage',
    label: 'Usage',
    icon: Activity,
    title: 'Usage',
    description: 'Session volume, runtime activity, and local operational footprint.',
    items: [
      { label: 'Active sessions today', value: '18', hint: 'Includes direct chats, delegations, and project threads.' },
      { label: 'Bridge handoffs', value: '7', hint: 'Cross-runtime requests sent through the local gateway.' },
      { label: 'Recent compactions', value: '3', hint: 'Token-aware session compactions in the last 24 hours.' },
      { label: 'Storage footprint', value: '2.4 GB', hint: 'Local sessions, artifacts, and cached workspace state.' },
    ],
  },
  {
    id: 'mcp',
    label: 'MCP servers',
    icon: Network,
    title: 'MCP Servers',
    description: 'Connected model context providers, tool servers, and their availability.',
    items: [
      { label: 'Connected servers', value: '5 active', hint: 'Local, GitHub, bridge telemetry, notes, and prompt packs.' },
      { label: 'Latency policy', value: 'Prefer local first', hint: 'Uses lower-latency local MCP endpoints whenever possible.' },
      { label: 'Auth refresh', value: 'Automatic', hint: 'Refreshes compatible connectors before expiration.' },
      { label: 'Fallback mode', value: 'Graceful degradation', hint: 'UI keeps loading even if one server becomes unavailable.' },
    ],
  },
  {
    id: 'git',
    label: 'Git',
    icon: FolderOpen,
    title: 'Git',
    description: 'Repository-aware defaults for sync, review, and change safety.',
    items: [
      { label: 'Auto-fetch', value: 'Manual', hint: 'Repository data refreshes only when you request it.' },
      { label: 'Conflict policy', value: 'Never overwrite local work', hint: 'Protects edited files and user changes by default.' },
      { label: 'Review mode', value: 'Findings first', hint: 'Shows bugs and regressions before summaries.' },
      { label: 'Branch preference', value: 'Current workspace branch', hint: 'New tasks stay aligned with the active branch.' },
    ],
  },
  {
    id: 'environments',
    label: 'Environments',
    icon: Bot,
    title: 'Environments',
    description: 'Runtime environments, local tools, and sandbox expectations.',
    items: [
      { label: 'Primary environment', value: 'Local worktree', hint: 'Uses your current workspace as the default execution environment.' },
      { label: 'Shell', value: 'zsh', hint: 'Default interactive shell for commands and scripts.' },
      { label: 'Python access', value: 'Available', hint: 'Used only when simpler shell edits are not suitable.' },
      { label: 'Network mode', value: 'Enabled', hint: 'Allows bridge checks, docs lookup, and remote actions when needed.' },
    ],
  },
  {
    id: 'worktrees',
    label: 'Worktrees',
    icon: ArrowRightLeft,
    title: 'Worktrees',
    description: 'Branch-isolated work surfaces and their lifecycle preferences.',
    items: [
      { label: 'Default pattern', value: 'feature/<task>', hint: 'Suggested naming scheme for new worktrees.' },
      { label: 'Cleanup policy', value: 'Manual review', hint: 'Leaves worktrees intact until you confirm cleanup.' },
      { label: 'Shared caches', value: 'Enabled', hint: 'Speeds up installs and builds across sibling worktrees.' },
      { label: 'Archived snapshots', value: 'Keep metadata only', hint: 'Preserves branch references without full workspace state.' },
    ],
  },
  {
    id: 'archived',
    label: 'Archived chats',
    icon: MessageSquare,
    title: 'Archived Chats',
    description: 'Archived threads, retention policy, and recovery behavior.',
    items: [
      { label: 'Retention', value: '180 days', hint: 'Archived chats remain searchable for six months.' },
      { label: 'Restore behavior', value: 'Open in place', hint: 'Recovered threads reappear in their original section.' },
      { label: 'Artifact links', value: 'Preserved', hint: 'Archived threads keep bridge traces and attachments intact.' },
      { label: 'Compaction mode', value: 'Metadata only after archive', hint: 'Reduces token cost while keeping context discoverable.' },
    ],
  },
] as const;
