import type { AssembleKordiShellSlotsArgs } from './kordiShellSlots.types';

export type RightDetailShellArgs = Pick<AssembleKordiShellSlotsArgs,
  | 'isNativeShell'
  | 'activeNav'
  | 'activeDetailTab'
  | 'setActiveDetailTab'
  | 'setIsDetailPanelCollapsed'
  | 'activeSourcePreview'
  | 'setActiveSourcePreview'
  | 'activeArtifactId'
  | 'setActiveArtifactId'
  | 'activeChatArtifacts'
  | 'activeProjectArtifacts'
  | 'activeProject'
  | 'activeProjectSession'
  | 'activeProjectLastMessage'
  | 'setActiveNav'
  | 'setActiveConvId'
  | 'getStatusBadgeClass'
  | 'desktopLiveTurn'
  | 'activeConv'
  | 'activeConvHasSubtitle'
  | 'activeLastMessage'
  | 'activeConversationUsesCollaboration'
  | 'activeCollaborationConversationHost'
  | 'activeCollaborationConversation'
  | 'activeCollaborationAwaitingReply'
  | 'isCollaborationSyncing'
  | 'lastCollaborationSyncAtLabel'
  | 'activeSessionProject'
  | 'activeQueuedDesktopMessages'
  | 'chatTranscriptScrollRef'
>;
