//! Every embedded Postgres migration, in version order.
//!
//! Versions are strictly increasing and never reused. Gaps are allowed, so a
//! migration developed in parallel can take a later version without
//! renumbering one that may already be recorded somewhere.

pub(super) struct EmbeddedMigration {
    pub(super) version: i64,
    pub(super) description: &'static str,
    pub(super) sql: &'static str,
}

/// One embedded migration: its version, description, and file in `migrations/`.
/// The `version:` label keeps each entry searchable by its version.
macro_rules! migration {
    (version: $version:literal, $description:literal, $file:literal) => {
        EmbeddedMigration {
            version: $version,
            description: $description,
            sql: include_str!(concat!("../../../migrations/", $file)),
        }
    };
}

// One entry per line keeps the table readable; rustfmt would spread each
// entry over several lines.
#[rustfmt::skip]
pub(super) const EMBEDDED_MIGRATIONS: &[EmbeddedMigration] = &[
    migration!(version: 1, "initial cloud schema", "0001_initial.sql"),
    migration!(version: 2, "cloud_attachments table", "0002_attachments.sql"),
    migration!(version: 3, "cloud_contact_requests + approval flow", "0003_contact_requests.sql"),
    migration!(version: 4, "cloud_messages table", "0004_cloud_messages.sql"),
    migration!(version: 5, "cloud OAuth state table", "0005_oauth_states.sql"),
    migration!(version: 6, "allow self cloud messages", "0006_allow_self_cloud_messages.sql"),
    migration!(version: 7, "cloud message session ids", "0007_cloud_message_session_ids.sql"),
    migration!(version: 8, "cloud message attachment links", "0008_cloud_message_attachments.sql"),
    migration!(version: 9, "cloud sync events", "0009_cloud_sync_events.sql"),
    migration!(version: 10, "cloud session forks lineage", "0010_cloud_session_forks.sql"),
    migration!(version: 11, "direct person cloud session ids",
        "0011_direct_person_session_ids.sql"),
    migration!(version: 12, "cloud sync event session payloads",
        "0012_cloud_sync_event_session_payloads.sql"),
    migration!(version: 13, "cloud session activity", "0013_cloud_session_activity.sql"),
    migration!(version: 14, "cloud session visibility", "0014_cloud_session_visibility.sql"),
    migration!(version: 17, "cloud device presence", "0017_cloud_device_presence.sql"),
    migration!(version: 18, "cloud agent fallback runs", "0018_cloud_agent_fallback_runs.sql"),
    migration!(version: 19, "cloud agent provider auth snapshots",
        "0019_cloud_agent_provider_auth_snapshots.sql"),
    migration!(version: 20, "cloud agent sandboxes", "0020_cloud_agent_sandboxes.sql"),
    migration!(version: 21, "cloud agent run artifacts", "0021_cloud_agent_run_artifacts.sql"),
    migration!(version: 22, "scheduled task tool", "0022_scheduled_task_tool.sql"),
    migration!(version: 23, "cloud session pinned messages", "0023_cloud_session_pins.sql"),
    migration!(version: 24, "backfill stranded scheduled tasks",
        "0024_backfill_stranded_scheduled_tasks.sql"),
    migration!(version: 25, "cloud agent definitions", "0025_cloud_agent_definitions.sql"),
    migration!(version: 26, "cloud agent participant sharing",
        "0026_cloud_agent_participant_sharing.sql"),
    migration!(version: 28, "cloud read cursors", "0028_cloud_read_cursors.sql"),
    migration!(version: 29, "backfill cloud read cursors", "0029_backfill_cloud_read_cursors.sql"),
    migration!(version: 30, "mark self cloud messages read",
        "0030_mark_self_cloud_messages_read.sql"),
    migration!(version: 31, "cloud message attachment previews",
        "0031_cloud_message_attachment_previews.sql"),
    migration!(version: 32, "cloud message idempotency", "0032_cloud_message_idempotency.sql"),
    migration!(version: 33, "cloud session titles", "0033_cloud_session_titles.sql"),
    migration!(version: 35, "global support", "0035_global_support.sql"),
    migration!(version: 36, "public Kordi ids and app invitations",
        "0036_public_kordi_ids_and_app_invitations.sql"),
    migration!(version: 44, "group invitations", "0044_group_invitations.sql"),
    migration!(version: 45, "cloud message server receive order",
        "0045_cloud_message_server_received_at.sql"),
    migration!(version: 46, "cloud agent runtime routes", "0046_cloud_agent_runtime_routes.sql"),
    migration!(version: 47, "create reliable canonical chat sync",
        "0047_reliable_chat_sync_v2.sql"),
    migration!(version: 48, "backfill retained chat into canonical chat sync",
        "0048_backfill_reliable_chat_sync_v2.sql"),
    migration!(version: 49, "relink migrated agent responses to canonical requests",
        "0049_relink_legacy_agent_responses.sql"),
    migration!(version: 50, "canonical Cloud-agent artifact links",
        "0050_chat_v2_artifact_links.sql"),
    migration!(version: 51, "retire superseded chat storage and compatibility bridges",
        "0051_retire_chat_sync_v1.sql"),
    migration!(version: 52, "device authorizations and idempotent management operations",
        "0052_device_authorizations.sql"),
    migration!(version: 53, "coarse device location metadata",
        "0053_device_approximate_location.sql"),
    migration!(version: 54, "coarse OAuth device location metadata",
        "0054_oauth_device_approximate_location.sql"),
    migration!(version: 55, "call state and Apple notification tokens", "0055_calls.sql"),
    migration!(version: 56, "deduplicated message notification events",
        "0056_message_notification_events.sql"),
    migration!(version: 57, "durable per-device message notification delivery",
        "0057_message_notification_deliveries.sql"),
    migration!(version: 58, "verified meme media metadata", "0058_meme_media_metadata.sql"),
    migration!(version: 59, "account expressive media library",
        "0059_expressive_media_library.sql"),
    migration!(version: 60, "resumable attachment uploads",
        "0060_resumable_attachment_uploads.sql"),
    migration!(version: 61, "canonical generated and uploaded avatars",
        "0061_canonical_avatars.sql"),
    migration!(version: 62, "monotonic call revisions", "0062_call_revisions.sql"),
    migration!(version: 63, "account-scoped default self-agent sessions",
        "0063_account_scoped_default_self_agent_sessions.sql"),
    migration!(version: 64, "reference-backed uploaded avatar assets", "0064_avatar_assets.sql"),
    migration!(version: 65, "repair resumable attachment uploads",
        "0065_repair_resumable_attachment_uploads.sql"),
    migration!(version: 66, "quarantine legacy support conversations",
        "0066_quarantine_legacy_support_conversations.sql"),
    migration!(version: 67, "quarantine invalid support conversations",
        "0067_quarantine_invalid_support_conversations.sql"),
    migration!(version: 68, "cloud agent fallback system prompts",
        "0068_cloud_agent_system_prompts.sql"),
    migration!(version: 69, "account default agent profiles", "0069_default_agent_profiles.sql"),
    migration!(version: 70, "expressive media deletion tombstones",
        "0070_expressive_media_deletions.sql"),
    migration!(version: 71, "chat message edit and deletion", "0071_chat_message_mutations.sql"),
    migration!(version: 72, "chat list preferences", "0072_chat_list_preferences.sql"),
    migration!(version: 73, "chat manual unread preference", "0073_chat_manual_unread.sql"),
    migration!(version: 74, "group space preferences", "0074_group_space_preferences.sql"),
    migration!(version: 75, "chat group catalog", "0075_chat_group_catalog.sql"),
    migration!(version: 76, "remove group session forks", "0076_remove_group_session_forks.sql"),
    migration!(version: 77, "remove group personal titles",
        "0077_remove_group_personal_titles.sql"),
    migration!(version: 78, "normalize group space ids", "0078_normalize_group_space_ids.sql"),
    migration!(version: 79, "default group channel titles",
        "0079_default_group_channel_titles.sql"),
    migration!(version: 80, "enforce canonical direct conversation identity",
        "0080_enforce_direct_conversation_identity.sql"),
    migration!(version: 81, "agent_execution_ownership", "0081_agent_execution_ownership.sql"),
    migration!(version: 82, "reconcile rolling digest schema", "0082_reconcile_rolling_digest.sql"),
    migration!(version: 83, "model agent subsessions", "0083_model_agent_subsessions.sql"),
    migration!(version: 84, "subsession conversations", "0084_subsession_conversations.sql"),
    migration!(version: 85, "subsession execution clock", "0085_subsession_execution_clock.sql"),
    migration!(version: 86, "per-member thread read cursors", "0086_thread_read_cursors.sql"),
    migration!(version: 87, "immutable agent turn identity", "0087_agent_turn_identity.sql"),
    migration!(version: 88, "indexed thread attention and independent unread totals",
        "0088_thread_attention.sql"),
    migration!(version: 89, "preserve legacy conversation and execution identities",
        "0089_legacy_identity_compatibility.sql"),
    migration!(version: 90, "recover historical channel names without exposing private titles",
        "0090_preserve_group_channel_names.sql"),
    migration!(version: 91, "add independently scoped attachment reactions and private visibility",
        "0091_chat_attachment_actions.sql"),
    migration!(version: 92, "retain independently scoped pin and unpin history",
        "0092_session_pin_history.sql"),
    migration!(version: 93, "recover retained pin history without blocking live capture",
        "0093_backfill_session_pin_history.sql"),
    migration!(version: 94, "shared plan cards for group-chat coordination", "0094_plan_cards.sql"),
    migration!(version: 95, "pip conversation sweep state", "0095_pip_conversation_state.sql"),
    migration!(version: 96, "plan card vote options", "0096_plan_card_options.sql"),
    migration!(version: 97, "digest change tracking", "0097_digest_change_tracking.sql"),
    migration!(version: 98, "digest failure backoff", "0098_digest_failure_backoff.sql"),
    migration!(version: 99, "durable plan-card projection and immutable PiP context",
        "0099_plan_card_projection_and_pip_context.sql"),
    migration!(version: 100, "provider auth profile labels",
        "0100_provider_auth_profile_labels.sql"),
    migration!(version: 101, "provider auth model hint", "0101_provider_auth_model_hint.sql"),
    migration!(version: 102, "provider auth login sessions",
        "0102_provider_auth_login_sessions.sql"),
    migration!(version: 103, "provider auth login session method",
        "0103_provider_auth_login_session_method.sql"),
    migration!(version: 104, "provider auth payload version",
        "0104_provider_auth_payload_version.sql"),
    migration!(version: 105, "provider auth snapshot readiness",
        "0105_provider_auth_snapshot_readiness.sql"),
    migration!(version: 106, "private OMP runtime replay state", "0106_omp_runtime_state.sql"),
    migration!(version: 107, "account-scoped desktop projects", "0107_chat_projects.sql"),
    migration!(version: 108, "session pin stacks", "0108_session_pin_stacks.sql"),
    migration!(version: 109, "session-bound realtime tickets", "0109_realtime_ticket_sessions.sql"),
    migration!(version: 113, "runner run token hash", "0113_runner_run_token_hash.sql"),
    migration!(version: 114, "desktop device proofs", "0114_desktop_device_proofs.sql"),
    migration!(version: 117, "account email verification", "0117_account_email_verification.sql"),
    migration!(version: 118, "OMP state replay flag", "0118_omp_state_replayable.sql"),
];
